name: ShareYouSee
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=production
      - PORT=3002
    command: node server/index.mjs
